/**
 * Payables — REQ-AP-001 Stage 4, PD / ASYCUDA (§16). Migration 0233.
 *
 * The customs pre-declaration, one row per registration. An import may have
 * several; a rejected or expired PD is re-registered as a new row that names
 * the one it supersedes, so the old one stays exactly as customs left it.
 * Every status a PD has had is a row of its history (append-only), with where
 * the news came from — the officer, an ASYCUDA screenshot, a pasted ASYCUDA
 * list, or the sweep.
 */
import { sql } from 'drizzle-orm';
import { boolean, date, index, pgTable, smallint, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';
import { appUser, branch } from './platform';
import { bank } from './item';
import { payable } from './payables';

/** The ASYCUDA statuses, with the flags the rules read (R4). */
export const pdStatus = pgTable('pd_status', {
  code: text('code').primaryKey(),
  name: text('name').notNull(),
  asycudaLabel: text('asycuda_label').notNull(),
  sequence: smallint('sequence').notNull(),
  allowsPayment: boolean('allows_payment').notNull().default(false),
  isTerminal: boolean('is_terminal').notNull().default(false),
  isExpired: boolean('is_expired').notNull().default(false),
  active: boolean('active').notNull().default(true),
  createdBy: uuid('created_by').references(() => appUser.id),
});

export const customsPd = pgTable(
  'customs_pd',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    pdNo: text('pd_no').notNull(),
    payableId: uuid('payable_id').references(() => payable.id),
    branchCode: text('branch_code')
      .notNull()
      .references(() => branch.code),
    registrationDate: date('registration_date').notNull(),
    /** Generated by the database from the registration date. */
    registrationYear: smallint('registration_year').generatedAlwaysAs(
      sql`extract(year from registration_date)::smallint`,
    ),
    expiryDate: date('expiry_date').notNull(),
    bankCode: text('bank_code').references(() => bank.code),
    bankSwift: text('bank_swift'),
    statusCode: text('status_code')
      .notNull()
      .default('submitted')
      .references(() => pdStatus.code),
    statusDate: date('status_date').notNull(),
    supersedesPdId: uuid('supersedes_pd_id'),
    lastNote: text('last_note'),
    source: text('source').notNull().default('erp'),
    sourceRow: text('source_row'),
    createdBy: uuid('created_by')
      .notNull()
      .references(() => appUser.id),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('customs_pd_no_year_uniq').on(t.pdNo, t.registrationYear),
    index('customs_pd_payable_idx').on(t.payableId),
  ],
);

export const PD_HISTORY_SOURCES = ['user', 'asycuda_screenshot', 'asycuda_list', 'sweep', 'sheet_import'] as const;
export type PdHistorySource = (typeof PD_HISTORY_SOURCES)[number];

/** Append-only (0233 trigger). */
export const customsPdStatusHistory = pgTable(
  'customs_pd_status_history',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    pdId: uuid('pd_id')
      .notNull()
      .references(() => customsPd.id),
    statusCode: text('status_code')
      .notNull()
      .references(() => pdStatus.code),
    effectiveDate: date('effective_date').notNull(),
    source: text('source').$type<PdHistorySource>().notNull(),
    note: text('note'),
    attachmentId: uuid('attachment_id'),
    recordedBy: uuid('recorded_by').references(() => appUser.id),
    recordedAt: timestamp('recorded_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('customs_pd_status_history_pd_idx').on(t.pdId, t.recordedAt)],
);
