/**
 * Payables — REQ-AP-001 Stage 4, PD / ASYCUDA (§16). Migration 0233.
 *
 * The customs pre-declaration, one row per registration. An import may have
 * several; a rejected or expired PD is re-registered as a new row that names
 * the one it supersedes, so the old one stays exactly as customs left it.
 * Every status a PD has had is a row of its history (append-only), with where
 * the news came from — the officer, an ASYCUDA screenshot, a pasted ASYCUDA
 * list, or the sweep.
 */
import { sql } from 'drizzle-orm';
import { boolean, date, index, integer, jsonb, pgTable, smallint, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';
import { appUser, branch } from './platform';
import { bank } from './item';
import { payable } from './payables';

/** The ASYCUDA statuses, with the flags the rules read (R4). */
export const pdStatus = pgTable('pd_status', {
  code: text('code').primaryKey(),
  name: text('name').notNull(),
  asycudaLabel: text('asycuda_label').notNull(),
  sequence: smallint('sequence').notNull(),
  allowsPayment: boolean('allows_payment').notNull().default(false),
  isTerminal: boolean('is_terminal').notNull().default(false),
  isExpired: boolean('is_expired').notNull().default(false),
  active: boolean('active').notNull().default(true),
  createdBy: uuid('created_by').references(() => appUser.id),
});

export const customsPd = pgTable(
  'customs_pd',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    pdNo: text('pd_no').notNull(),
    payableId: uuid('payable_id').references(() => payable.id),
    branchCode: text('branch_code')
      .notNull()
      .references(() => branch.code),
    registrationDate: date('registration_date').notNull(),
    /** Generated by the database from the registration date. */
    registrationYear: smallint('registration_year').generatedAlwaysAs(
      sql`extract(year from registration_date)::smallint`,
    ),
    expiryDate: date('expiry_date').notNull(),
    bankCode: text('bank_code').references(() => bank.code),
    bankSwift: text('bank_swift'),
    statusCode: text('status_code')
      .notNull()
      .default('submitted')
      .references(() => pdStatus.code),
    statusDate: date('status_date').notNull(),
    supersedesPdId: uuid('supersedes_pd_id'),
    lastNote: text('last_note'),
    source: text('source').notNull().default('erp'),
    sourceRow: text('source_row'),
    createdBy: uuid('created_by')
      .notNull()
      .references(() => appUser.id),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('customs_pd_no_year_uniq').on(t.pdNo, t.registrationYear),
    index('customs_pd_payable_idx').on(t.payableId),
  ],
);

export const PD_HISTORY_SOURCES = ['user', 'asycuda_screenshot', 'asycuda_list', 'sweep', 'sheet_import'] as const;
export type PdHistorySource = (typeof PD_HISTORY_SOURCES)[number];

/** Append-only (0233 trigger). */
export const customsPdStatusHistory = pgTable(
  'customs_pd_status_history',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    pdId: uuid('pd_id')
      .notNull()
      .references(() => customsPd.id),
    statusCode: text('status_code')
      .notNull()
      .references(() => pdStatus.code),
    effectiveDate: date('effective_date').notNull(),
    source: text('source').$type<PdHistorySource>().notNull(),
    note: text('note'),
    attachmentId: uuid('attachment_id'),
    recordedBy: uuid('recorded_by').references(() => appUser.id),
    recordedAt: timestamp('recorded_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index('customs_pd_status_history_pd_idx').on(t.pdId, t.recordedAt)],
);

/**
 * One reading of the ASYCUDA document list — 0257.
 *
 * The screen used to read a pasted list, show the difference and keep
 * nothing. A declaration's status is what releases a payment, so where that
 * reading came from and when has to be answerable afterwards: the lines as
 * they were read, the file they came from, the difference computed at that
 * moment, who read it and who applied it.
 *
 * `report` is the difference as it stood, kept whole rather than in a child
 * table — the same shape `legacy_import_run.report` uses, and for the same
 * reason: it is a record of what was seen, never queried across runs.
 */
export const asycudaRun = pgTable(
  'asycuda_run',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    /** IMPROVEMENT-002 — the reading as a document: ASY-{YYYY}-{SERIAL} (0268). */
    runNo: text('run_no'),
    /** `file` when a report was uploaded, `paste` when the list was typed. */
    source: text('source').$type<'file' | 'paste'>().notNull(),
    fileNames: jsonb('file_names').notNull().$type<string[]>().default([]),
    /** SHA-256 over the lines as read — what "the same list again" means. */
    textSha256: text('text_sha256').notNull(),
    lineText: text('line_text').notNull(),
    report: jsonb('report').notNull(),
    lineCount: integer('line_count').notNull().default(0),
    changeCount: integer('change_count').notNull().default(0),
    unreadableCount: integer('unreadable_count').notNull().default(0),
    status: text('status').$type<'previewed' | 'applied'>().notNull().default('previewed'),
    readBy: uuid('read_by')
      .notNull()
      .references(() => appUser.id),
    readAt: timestamp('read_at', { withTimezone: true }).notNull().defaultNow(),
    appliedBy: uuid('applied_by').references(() => appUser.id),
    appliedAt: timestamp('applied_at', { withTimezone: true }),
  },
  (t) => [index('asycuda_run_read_idx').on(t.readAt)],
);
