-- ===========================================================================
-- Phase 01 — PLATFORM CORE
--
-- 01.1 identity record · 01.2 permissions and data scope · 01.3 Department
-- Manager toggle · 01.4 audit · 01.5 document numbering.
--
-- The table DDL below is generated by drizzle-kit from
-- src/server/db/schema/platform.ts. Everything after the marked line is
-- hand-authored, because the controls it carries — RLS policies, append-only
-- triggers, REVOKEs and the numbering functions — are not expressible in the
-- schema generator, and they are the part that actually enforces §5, §24 and
-- §25. Reviewed as part of the release record required by §25.
--
-- ── On the Phase 00 spike ───────────────────────────────────────────────────
-- 0000_phase00_spike.sql said its spike_ objects would be dropped in Phase 01.
-- They are kept until Phase 02 instead. The spike is the only place where the
-- money/rate precision (A4) and idempotent-posting (A5) guarantees are proved
-- against the database, and Phase 02 is where the real journal tables take that
-- over. Dropping the proof before its replacement exists would leave those two
-- constraints unverified across the whole of Phase 01. This is a build-
-- sequencing decision only — no business rule, accounting rule or permission is
-- affected (§28.1 is not engaged).
-- ===========================================================================

CREATE TYPE "public"."audit_outcome" AS ENUM('success', 'denied', 'failure');--> statement-breakpoint
CREATE TYPE "public"."permission_verb" AS ENUM('view', 'create', 'edit_draft', 'submit', 'approve', 'execute', 'post', 'reverse_cancel', 'print', 'export', 'import', 'configure', 'administer');--> statement-breakpoint
CREATE TABLE "app_user" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" text NOT NULL,
	"display_name" text NOT NULL,
	"is_super_user" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "app_user_email_shape" CHECK (position('@' in "app_user"."email") > 1)
);
--> statement-breakpoint
CREATE TABLE "audit_event" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "audit_event_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"actor_user_id" uuid,
	"action" text NOT NULL,
	"object_type" text NOT NULL,
	"object_id" text,
	"branch_code" text,
	"before_value" jsonb,
	"after_value" jsonb,
	"reason" text,
	"outcome" "audit_outcome" NOT NULL,
	"session_id" text,
	"request_id" text,
	"client_ip" "inet",
	"related_object_id" text
);
--> statement-breakpoint
CREATE TABLE "branch" (
	"code" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "department" (
	"code" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "doc_number_allocation" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "doc_number_allocation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"sequence_key" text NOT NULL,
	"scope_key" text NOT NULL,
	"serial" bigint NOT NULL,
	"document_no" text NOT NULL,
	"allocated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"allocated_by" uuid
);
--> statement-breakpoint
CREATE TABLE "doc_sequence" (
	"key" text PRIMARY KEY NOT NULL,
	"prefix" text NOT NULL,
	"pattern" text NOT NULL,
	"padding" smallint DEFAULT 6 NOT NULL,
	"scope_branch" boolean DEFAULT false NOT NULL,
	"scope_year" boolean DEFAULT false NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "doc_sequence_pattern_has_serial" CHECK ("doc_sequence"."pattern" like '%{SERIAL}%'),
	CONSTRAINT "doc_sequence_padding_range" CHECK ("doc_sequence"."padding" between 1 and 18),
	CONSTRAINT "doc_sequence_branch_pattern" CHECK (not "doc_sequence"."scope_branch" or "doc_sequence"."pattern" like '%{BRANCH}%'),
	CONSTRAINT "doc_sequence_year_pattern" CHECK (not "doc_sequence"."scope_year" or ("doc_sequence"."pattern" like '%{YY}%' or "doc_sequence"."pattern" like '%{YYYY}%'))
);
--> statement-breakpoint
CREATE TABLE "role" (
	"code" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"is_system" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "role_grant" (
	"role_code" text NOT NULL,
	"object" text NOT NULL,
	"verb" "permission_verb" NOT NULL,
	CONSTRAINT "role_grant_role_code_object_verb_pk" PRIMARY KEY("role_code","object","verb")
);
--> statement-breakpoint
CREATE TABLE "user_branch_scope" (
	"user_id" uuid NOT NULL,
	"branch_code" text NOT NULL,
	CONSTRAINT "user_branch_scope_user_id_branch_code_pk" PRIMARY KEY("user_id","branch_code")
);
--> statement-breakpoint
CREATE TABLE "user_department_scope" (
	"user_id" uuid NOT NULL,
	"department_code" text NOT NULL,
	"is_manager" boolean DEFAULT false NOT NULL,
	CONSTRAINT "user_department_scope_user_id_department_code_pk" PRIMARY KEY("user_id","department_code")
);
--> statement-breakpoint
CREATE TABLE "user_role" (
	"user_id" uuid NOT NULL,
	"role_code" text NOT NULL,
	"granted_at" timestamp with time zone DEFAULT now() NOT NULL,
	"granted_by" uuid,
	CONSTRAINT "user_role_user_id_role_code_pk" PRIMARY KEY("user_id","role_code")
);
--> statement-breakpoint
ALTER TABLE "audit_event" ADD CONSTRAINT "audit_event_actor_user_id_app_user_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_event" ADD CONSTRAINT "audit_event_branch_code_branch_code_fk" FOREIGN KEY ("branch_code") REFERENCES "public"."branch"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "doc_number_allocation" ADD CONSTRAINT "doc_number_allocation_sequence_key_doc_sequence_key_fk" FOREIGN KEY ("sequence_key") REFERENCES "public"."doc_sequence"("key") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "doc_number_allocation" ADD CONSTRAINT "doc_number_allocation_allocated_by_app_user_id_fk" FOREIGN KEY ("allocated_by") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "role_grant" ADD CONSTRAINT "role_grant_role_code_role_code_fk" FOREIGN KEY ("role_code") REFERENCES "public"."role"("code") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_branch_scope" ADD CONSTRAINT "user_branch_scope_user_id_app_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_branch_scope" ADD CONSTRAINT "user_branch_scope_branch_code_branch_code_fk" FOREIGN KEY ("branch_code") REFERENCES "public"."branch"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_department_scope" ADD CONSTRAINT "user_department_scope_user_id_app_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_department_scope" ADD CONSTRAINT "user_department_scope_department_code_department_code_fk" FOREIGN KEY ("department_code") REFERENCES "public"."department"("code") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_role" ADD CONSTRAINT "user_role_user_id_app_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_role" ADD CONSTRAINT "user_role_role_code_role_code_fk" FOREIGN KEY ("role_code") REFERENCES "public"."role"("code") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_role" ADD CONSTRAINT "user_role_granted_by_app_user_id_fk" FOREIGN KEY ("granted_by") REFERENCES "public"."app_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "app_user_email_uniq" ON "app_user" USING btree (lower("email"));--> statement-breakpoint
CREATE INDEX "audit_event_object_idx" ON "audit_event" USING btree ("object_type","object_id","occurred_at");--> statement-breakpoint
CREATE INDEX "audit_event_actor_idx" ON "audit_event" USING btree ("actor_user_id","occurred_at");--> statement-breakpoint
CREATE INDEX "audit_event_action_idx" ON "audit_event" USING btree ("action","occurred_at");--> statement-breakpoint
CREATE UNIQUE INDEX "doc_number_allocation_serial_uniq" ON "doc_number_allocation" USING btree ("sequence_key","scope_key","serial");--> statement-breakpoint
CREATE UNIQUE INDEX "doc_number_allocation_document_no_uniq" ON "doc_number_allocation" USING btree ("document_no");--> statement-breakpoint

-- ===========================================================================
-- HAND-AUTHORED FROM HERE. Everything above is generated.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- The request security context.
--
-- Set per transaction by src/server/db/client.ts with set_config(..., true),
-- so it is transaction-local and cannot leak to the next request that borrows
-- the same pooled connection.
--
-- current_setting(..., true) returns NULL when unset, and every policy below
-- compares against it. An unscoped connection therefore sees nothing — that is
-- deny-by-default (§25) expressed as a database property rather than as a
-- convention the next developer has to know about.
-- ---------------------------------------------------------------------------
CREATE FUNCTION app_current_user() RETURNS uuid
LANGUAGE sql STABLE AS $$
  SELECT nullif(current_setting('app.user_id', true), '')::uuid;
$$;--> statement-breakpoint

CREATE FUNCTION app_current_branch() RETURNS text
LANGUAGE sql STABLE AS $$
  SELECT nullif(current_setting('app.branch_code', true), '');
$$;--> statement-breakpoint

-- §5.1 — "Super Users retain full administration access."
--
-- This flag is set by the same trusted server code that sets the user id, from
-- app_user.is_super_user. It is a convenience for the policies below, not an
-- independent authority: a caller who could forge it could already forge the
-- user id. The permission decision itself lives in src/server/domain/permissions.ts.
CREATE FUNCTION app_is_super_user() RETURNS boolean
LANGUAGE sql STABLE AS $$
  SELECT coalesce(nullif(current_setting('app.is_super_user', true), '')::boolean, false);
$$;--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Append-only enforcement (§5.4, §24, TECHSTACK A2)
--
-- Generic, because Phase 02 reuses it for posted journals, subledger entries
-- and inventory movements. Two layers, because either alone is insufficient:
--   1. the app role is never granted UPDATE/DELETE  — stops the application
--   2. this trigger                                  — stops everyone else,
--      including the owner role and any future migration that forgets
-- ---------------------------------------------------------------------------
CREATE FUNCTION reject_mutation() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION
    'Table % is append-only: % is not permitted. Corrections create a new linked entry (blueprint §24).',
    TG_TABLE_NAME, TG_OP
    USING ERRCODE = 'restrict_violation';
END;
$$;--> statement-breakpoint

CREATE TRIGGER audit_event_append_only
  BEFORE UPDATE OR DELETE ON audit_event
  FOR EACH ROW EXECUTE FUNCTION reject_mutation();--> statement-breakpoint

-- An issued document number is a fact, not a field. §14.2: numbers are
-- "generated automatically and never reused" — an editable allocation row would
-- make the gap report arguable.
CREATE TRIGGER doc_number_allocation_append_only
  BEFORE UPDATE OR DELETE ON doc_number_allocation
  FOR EACH ROW EXECUTE FUNCTION reject_mutation();--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Row-level security on the audit trail (§22, §25)
--
-- FORCE is the critical word: without it the table owner bypasses the policy
-- and every scope test passes for the wrong reason.
--
-- Read:  your branch only. Events with no branch (a failed sign-in, a
--        configuration change) are administration-wide and readable only by a
--        Super User.
-- Write: your branch, or no branch. Never another branch — an actor cannot
--        plant an event in a branch they cannot see.
-- ---------------------------------------------------------------------------
ALTER TABLE audit_event ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE audit_event FORCE  ROW LEVEL SECURITY;--> statement-breakpoint

CREATE POLICY audit_event_branch_scope ON audit_event
  USING (
    app_is_super_user()
    OR (branch_code IS NOT NULL AND branch_code = app_current_branch())
  )
  WITH CHECK (
    app_is_super_user()
    OR branch_code IS NULL
    OR branch_code = app_current_branch()
  );--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- 01.5 — document numbering
--
-- The counter is a PostgreSQL sequence, one per (document type, reset scope),
-- created on first use. nextval() is deliberately NOT transactional: a rolled
-- back document must not hand its number to the next document (§14.2, "never
-- reused"). The hole it leaves is reported by document_number_gaps() below,
-- which is the §24 "sequence gaps" report.
--
-- The sequence name is derived through md5 rather than by interpolating the
-- key: these functions run SECURITY DEFINER, so a name built from caller input
-- would be an injection point into an identifier. md5 is used for shape, not
-- for secrecy — it yields a fixed-length, always-valid identifier.
-- ---------------------------------------------------------------------------
CREATE FUNCTION doc_sequence_name(p_key text, p_scope text) RETURNS text
LANGUAGE sql IMMUTABLE AS $$
  SELECT 'docseq_' || md5(p_key || '|' || coalesce(p_scope, ''));
$$;--> statement-breakpoint

CREATE FUNCTION next_document_serial(p_key text, p_scope text DEFAULT '') RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE
  v_seq    text;
  v_serial bigint;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM doc_sequence WHERE key = p_key AND active) THEN
    RAISE EXCEPTION 'Unknown or inactive document sequence: %', p_key
      USING ERRCODE = 'invalid_parameter_value';
  END IF;

  v_seq := doc_sequence_name(p_key, p_scope);

  IF to_regclass(v_seq) IS NULL THEN
    -- Serialise creation only. Taking this lock on every allocation would
    -- serialise the whole document type for the length of each transaction.
    PERFORM pg_advisory_xact_lock(hashtext(v_seq));
    IF to_regclass(v_seq) IS NULL THEN
      EXECUTE format('CREATE SEQUENCE %I START 1', v_seq);
    END IF;
  END IF;

  EXECUTE format('SELECT nextval(%L)', v_seq) INTO v_serial;
  RETURN v_serial;
END;
$$;--> statement-breakpoint

-- §24 — "duplicate source references and sequence gaps" report.
--
-- A gap is a serial the sequence issued that never reached a committed
-- document. Expected to be small and explainable one row at a time; a growing
-- gap count is a signal that documents are failing after allocation.
CREATE FUNCTION document_number_gaps(p_key text, p_scope text DEFAULT '')
RETURNS TABLE (missing_serial bigint)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE
  v_seq    text;
  v_last   bigint;
  v_called boolean;
BEGIN
  v_seq := doc_sequence_name(p_key, p_scope);
  IF to_regclass(v_seq) IS NULL THEN
    RETURN; -- nothing ever issued, therefore nothing missing
  END IF;

  EXECUTE format('SELECT last_value, is_called FROM %I', v_seq) INTO v_last, v_called;
  IF NOT v_called THEN
    RETURN;
  END IF;

  RETURN QUERY
    SELECT s
      FROM generate_series(1::bigint, v_last) AS s
     WHERE NOT EXISTS (
             SELECT 1 FROM doc_number_allocation a
              WHERE a.sequence_key = p_key
                AND a.scope_key    = p_scope
                AND a.serial       = s);
END;
$$;--> statement-breakpoint

-- ---------------------------------------------------------------------------
-- Grants for the application role.
--
-- Granted per table rather than through ALTER DEFAULT PRIVILEGES, because
-- default privileges are per-database and this migration must produce the same
-- result against erp and against erp_test.
--
-- Guarded on the role existing so the schema still builds without it; the
-- application then simply cannot connect, which is the correct failure.
--
-- The shape of this block IS the control. Read it as a statement of what the
-- application may do:
--   · it may never UPDATE or DELETE an audit event or an issued number (§5.4, §14.2)
--   · it may never DELETE a user, branch or department — deactivate instead (§1.1)
--   · it may revoke a role or scope assignment, which is a DELETE on the join
--     tables only, and every such change is audited (§5.4)
-- ---------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'erp_app') THEN
    RAISE WARNING
      'Role erp_app does not exist — grants skipped. Run scripts/sql/00-init-roles.sql.';
    RETURN;
  END IF;

  GRANT USAGE ON SCHEMA public TO erp_app;

  REVOKE ALL ON branch, department, app_user, role, role_grant, user_role,
                user_branch_scope, user_department_scope, audit_event,
                doc_sequence, doc_number_allocation
    FROM erp_app;

  -- Configuration and master records: created and amended, never deleted.
  GRANT SELECT, INSERT, UPDATE ON branch       TO erp_app;
  GRANT SELECT, INSERT, UPDATE ON department   TO erp_app;
  GRANT SELECT, INSERT, UPDATE ON app_user     TO erp_app;
  GRANT SELECT, INSERT, UPDATE ON role         TO erp_app;
  GRANT SELECT, INSERT, UPDATE ON doc_sequence TO erp_app;

  -- Assignments: granting and revoking are both ordinary administration.
  GRANT SELECT, INSERT, UPDATE, DELETE ON role_grant            TO erp_app;
  GRANT SELECT, INSERT, UPDATE, DELETE ON user_role             TO erp_app;
  GRANT SELECT, INSERT, UPDATE, DELETE ON user_branch_scope     TO erp_app;
  GRANT SELECT, INSERT, UPDATE, DELETE ON user_department_scope TO erp_app;

  -- Append-only. The absence of UPDATE and DELETE here is the second half of
  -- the control the triggers above enforce.
  GRANT SELECT, INSERT ON audit_event            TO erp_app;
  GRANT SELECT, INSERT ON doc_number_allocation  TO erp_app;

  GRANT EXECUTE ON FUNCTION app_current_user()                  TO erp_app;
  GRANT EXECUTE ON FUNCTION app_current_branch()                TO erp_app;
  GRANT EXECUTE ON FUNCTION app_is_super_user()                 TO erp_app;
  GRANT EXECUTE ON FUNCTION doc_sequence_name(text, text)       TO erp_app;
  GRANT EXECUTE ON FUNCTION next_document_serial(text, text)    TO erp_app;
  GRANT EXECUTE ON FUNCTION document_number_gaps(text, text)    TO erp_app;
END;
$$;