-- ---------------------------------------------------------------------------
-- The Item Code is minted, not typed — by direction, 2026-09-26.
--
-- *"All Item Codes must be automatically generated by the system. There should
-- be no manual input field or manual editing for the Item Code, because we
-- need to completely avoid duplicate codes, incorrect entries, and human
-- errors."*
--
-- Until now an item's code was a slug of its name with a suffix when that slug
-- was taken — SOLAR, SOLAR_2 — and the field was editable, so two people
-- entering the same panel on the same day could and did produce two codes for
-- one thing. §3.1 asks for "one authoritative record and a unique system
-- identifier"; a name-derived code is neither.
--
-- It joins the chart of accounts, which has minted A000001 this way since
-- Phase 02, and every document, which has minted its own number since Phase
-- 01. One mechanism, not a third one for items.
--
-- The pattern is configurable on the Numbering screen like the rest. ITM-000001
-- rather than ITM000001 because an item code is read aloud across a warehouse,
-- and the separator is where the voice pauses.
-- ---------------------------------------------------------------------------
INSERT INTO doc_sequence (key, prefix, pattern, padding, scope_branch, scope_year) VALUES
  ('ITEM_CODE', 'ITM', '{PREFIX}-{SERIAL}', 6, false, false)
ON CONFLICT (key) DO NOTHING;--> statement-breakpoint

-- Nothing is renamed. An item already called SOLAR keeps that code, because it
-- is printed on documents that have already gone out; only the next one is
-- minted.
--
-- The counter starts past the highest code already in the minted shape, so if
-- somebody has typed ITM-000001 by hand the sequence cannot hand it out again.
-- Codes in any other shape are ignored: they cannot collide with ITM-nnnnnn.
-- The sequence itself is created here rather than waiting for the first
-- allocation, because setval needs something to set.
DO $$
DECLARE
  highest bigint;
  seq     text;
BEGIN
  seq := doc_sequence_name('ITEM_CODE', '');
  IF to_regclass(seq) IS NULL THEN
    EXECUTE format('CREATE SEQUENCE %I START 1', seq);
  END IF;

  SELECT coalesce(max(substring(code from '^ITM-([0-9]+)$')::bigint), 0)
    INTO highest
    FROM item;

  IF highest > 0 THEN
    PERFORM setval(seq, highest, true);
  END IF;
END $$;
