-- ---------------------------------------------------------------------------
-- Master-data codes are minted, not typed — customers, suppliers, warehouses,
-- payment terms, departments, cost centres and payment methods.
--
-- Operations build, Critical Rule 1 (2026-09-26):
--
--   *"Any code, number, ID, invoice number, bank/cash number, sequence, or
--   other identifier that is supposed to be generated by the system must be
--   automatically generated by the system. Users must NOT manually enter these
--   values."* — naming Supplier/Customer codes where the implementation defines
--   them as system-generated.
--
-- It did: each of these forms said "Left blank, it is made from the name" — a
-- code the system generated, in a field anybody could type over. That is the
-- pattern 0204 removed from items and 0205 from bank and cash accounts. The
-- same one mechanism now gives each of these its code.
--
--   Customer      CUS-000001        Supplier        SUP-000001
--   Warehouse     WH-0001           Payment Term    PT-0001
--   Department    DEP-0001          Cost Centre     CC-0001
--   Payment Method PM-0001
--
-- Three codes stay typed, on purpose. A branch code is a short mnemonic that
-- is printed inside every document number (API-BGW-2026-000001); a unit of
-- measure's code is its symbol (EA, KG); a role's code is the key its grants
-- are written against. None of them is a sequence.
--
-- A partner is a customer or a supplier when it is created, and its code says
-- which; if the same partner later takes the other role it keeps its code.
--
-- Nothing already created is renamed — its code is on documents that have gone
-- out. Each counter starts past the highest code already in its minted shape,
-- so a code somebody typed in that shape cannot be handed out a second time.
-- ---------------------------------------------------------------------------
INSERT INTO doc_sequence (key, prefix, pattern, padding, scope_branch, scope_year) VALUES
  ('CUSTOMER_CODE', 'CUS', '{PREFIX}-{SERIAL}', 6, false, false),
  ('SUPPLIER_CODE', 'SUP', '{PREFIX}-{SERIAL}', 6, false, false),
  ('WAREHOUSE_CODE', 'WH', '{PREFIX}-{SERIAL}', 4, false, false),
  ('PAYMENT_TERM_CODE', 'PT', '{PREFIX}-{SERIAL}', 4, false, false),
  ('DEPARTMENT_CODE', 'DEP', '{PREFIX}-{SERIAL}', 4, false, false),
  ('COST_CENTRE_CODE', 'CC', '{PREFIX}-{SERIAL}', 4, false, false),
  ('PAYMENT_METHOD_CODE', 'PM', '{PREFIX}-{SERIAL}', 4, false, false)
ON CONFLICT (key) DO NOTHING;--> statement-breakpoint

DO $$
DECLARE
  spec record;
  highest bigint;
  seq text;
BEGIN
  FOR spec IN
    SELECT 'CUSTOMER_CODE' AS key,
           (SELECT coalesce(max(substring(code from '^CUS-([0-9]+)$')::bigint), 0) FROM business_partner) AS top
    UNION ALL
    SELECT 'SUPPLIER_CODE',
           (SELECT coalesce(max(substring(code from '^SUP-([0-9]+)$')::bigint), 0) FROM business_partner)
    UNION ALL
    SELECT 'WAREHOUSE_CODE',
           (SELECT coalesce(max(substring(code from '^WH-([0-9]+)$')::bigint), 0) FROM warehouse)
    UNION ALL
    SELECT 'PAYMENT_TERM_CODE',
           (SELECT coalesce(max(substring(code from '^PT-([0-9]+)$')::bigint), 0) FROM payment_terms)
    UNION ALL
    SELECT 'DEPARTMENT_CODE',
           (SELECT coalesce(max(substring(code from '^DEP-([0-9]+)$')::bigint), 0) FROM department)
    UNION ALL
    SELECT 'COST_CENTRE_CODE',
           (SELECT coalesce(max(substring(code from '^CC-([0-9]+)$')::bigint), 0) FROM cost_centre)
    UNION ALL
    SELECT 'PAYMENT_METHOD_CODE',
           (SELECT coalesce(max(substring(code from '^PM-([0-9]+)$')::bigint), 0) FROM payment_method)
  LOOP
    seq := doc_sequence_name(spec.key, '');
    IF to_regclass(seq) IS NULL THEN
      EXECUTE format('CREATE SEQUENCE %I START 1', seq);
    END IF;
    highest := spec.top;
    IF highest > 0 THEN
      PERFORM setval(seq, highest, true);
    END IF;
  END LOOP;
END $$;
